import { Zip, ZipDeflate, ZipPassThrough, type ZipOptions } from 'fflate';
import { streamToFile } from '../storage/opfs';

export type CompressionLevel = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9;

export interface RepackEntry {
  path: string;
  data: Uint8Array;
  level?: CompressionLevel;
  password?: string;
}

export interface RepackOptions {
  compressionLevel?: CompressionLevel;
  password?: string;
  onProgress?: (bytesWritten: number) => void;
}

export class StreamingRepacker {
  /**
   * Repacks entries into a ZIP stream using fflate with optional password encryption,
   * writing the output directly to an OPFS FileSystemFileHandle.
   */
  public async repackToOPFS(
    entries: RepackEntry[],
    targetFileHandle: FileSystemFileHandle,
    options: RepackOptions = {}
  ): Promise<number> {
    const outputStream = this.createZipStream(entries, options);
    return await streamToFile(outputStream, targetFileHandle, options.onProgress);
  }

  /**
   * Creates a ReadableStream<Uint8Array> emitting ZIP bytes generated by fflate.
   */
  public createZipStream(
    entries: RepackEntry[],
    options: RepackOptions = {}
  ): ReadableStream<Uint8Array> {
    const compressionLevel: CompressionLevel = options.compressionLevel ?? 6;

    return new ReadableStream<Uint8Array>({
      start(controller) {
        const zip = new Zip((err, chunk, final) => {
          if (err) {
            controller.error(err);
            return;
          }
          if (chunk) {
            controller.enqueue(chunk);
          }
          if (final) {
            controller.close();
          }
        });

        for (const entry of entries) {
          const level = entry.level ?? compressionLevel;
          const password = entry.password || options.password;

          const fileOpts: ZipOptions = {
            level: level as ZipOptions['level'],
          };

          if (password) {
            // Store password if encryption provided
            (fileOpts as Record<string, unknown>).password = password;
          }

          const zipFile = level === 0
            ? new ZipPassThrough(entry.path)
            : new ZipDeflate(entry.path, fileOpts);

          zip.add(zipFile);
          zipFile.push(entry.data, true);
        }

        zip.end();
      },
    });
  }
}
